export enum TSchordEnum {
  C = "C",
  D = "D",
  E = "E",
  F = "F",
  G = "G",
  A = "A",
  B = "B",
  Db = "Db",
  Eb = "Eb",
  Gb = "Gb",
  Ab = "Ab",
  Bb = "Bb"
}

export const TSchordArray = [
  TSchordEnum.C,
  TSchordEnum.Db,
  TSchordEnum.D,
  TSchordEnum.Eb,
  TSchordEnum.E,
  TSchordEnum.F,
  TSchordEnum.Gb,
  TSchordEnum.G,
  TSchordEnum.Ab,
  TSchordEnum.A,
  TSchordEnum.Bb,
  TSchordEnum.B
];

export enum TSvariationEnum {
  Major = "Major",
  m = "m",
  msix = "m6",
  mseven = "m7",
  aug = "aug",
  dim = "dim",
  two = "2",
  six = "6",
  seven = "7",
  sustwo = "sus2",
  susfour = "sus4"
}

export const TSvariationArray = [
  TSvariationEnum.Major,
  TSvariationEnum.m,
  TSvariationEnum.msix,
  TSvariationEnum.mseven,
  TSvariationEnum.aug,
  TSvariationEnum.dim,
  TSvariationEnum.two,
  TSvariationEnum.six,
  TSvariationEnum.seven,
  TSvariationEnum.sustwo,
  TSvariationEnum.susfour
];

export enum TSchordVariationEnum {
  // C
  CMajor = "CMajor",
  Cm = "Cm",
  Cm6 = "Cm6",
  Cm7 = "Cm7",
  Caug = "Caug",
  Cdim = "Cdim",
  C2 = "C2",
  C6 = "C6",
  C7 = "C7",
  Csus2 = "Csus2",
  Csus4 = "Csus4",
  // Db
  DbMajor = "DbMajor",
  Dbm = "Dbm",
  Dbm6 = "Dbm6",
  Dbm7 = "Dbm7",
  Dbaug = "Dbaug",
  Dbdim = "Dbdim",
  Db2 = "Db2",
  Db6 = "Db6",
  Db7 = "Db7",
  Dbsus2 = "Dbsus2",
  Dbsus4 = "Dbsus4",
  // D
  DMajor = "DMajor",
  Dm = "Dm",
  Dm6 = "Dm6",
  Dm7 = "Dm7",
  Daug = "Daug",
  Ddim = "Ddim",
  D2 = "D2",
  D6 = "D6",
  D7 = "D7",
  Dsus2 = "Dsus2",
  Dsus4 = "Dsus4",
  // Eb
  EbMajor = "EbMajor",
  Ebm = "Ebm",
  Ebm6 = "Ebm6",
  Ebm7 = "Ebm7",
  Ebaug = "Ebaug",
  Ebdim = "Ebdim",
  Eb2 = "Eb2",
  Eb6 = "Eb6",
  Eb7 = "Eb7",
  Ebsus2 = "Ebsus2",
  Ebsus4 = "Ebsus4",
  // E
  EMajor = "EMajor",
  Em = "Em",
  Em6 = "Em6",
  Em7 = "Em7",
  Eaug = "Eaug",
  Edim = "Edim",
  E2 = "E2",
  E6 = "E6",
  E7 = "E7",
  Esus2 = "Esus2",
  Esus4 = "Esus4",
  // F
  FMajor = "FMajor",
  Fm = "Fm",
  Fm6 = "Fm6",
  Fm7 = "Fm7",
  Faug = "Faug",
  Fdim = "Fdim",
  F2 = "F2",
  F6 = "F6",
  F7 = "F7",
  TSus2 = "TSus2",
  TSus4 = "TSus4",
  // Gb
  GbMajor = "GbMajor",
  Gbm = "Gbm",
  Gbm6 = "Gbm6",
  Gbm7 = "Gbm7",
  Gbaug = "Gbaug",
  Gbdim = "Gbdim",
  Gb2 = "Gb2",
  Gb6 = "Gb6",
  Gb7 = "Gb7",
  Gbsus2 = "Gbsus2",
  Gbsus4 = "Gbsus4",
  // G
  GMajor = "GMajor",
  Gm = "Gm",
  Gm6 = "Gm6",
  Gm7 = "Gm7",
  Gaug = "Gaug",
  Gdim = "Gdim",
  G2 = "G2",
  G6 = "G6",
  G7 = "G7",
  Gsus2 = "Gsus2",
  Gsus4 = "Gsus4",
  // Ab
  AbMajor = "AbMajor",
  Abm = "Abm",
  Abm6 = "Abm6",
  Abm7 = "Abm7",
  Abaug = "Abaug",
  Abdim = "Abdim",
  Ab2 = "Ab2",
  Ab6 = "Ab6",
  Ab7 = "Ab7",
  Absus2 = "Absus2",
  Absus4 = "Absus4",
  // A
  AMajor = "AMajor",
  Am = "Am",
  Am6 = "Am6",
  Am7 = "Am7",
  Aaug = "Aaug",
  Adim = "Adim",
  A2 = "A2",
  A6 = "A6",
  A7 = "A7",
  Asus2 = "Asus2",
  Asus4 = "Asus4",
  // Bb
  BbMajor = "BbMajor",
  Bbm = "Bbm",
  Bbm6 = "Bbm6",
  Bbm7 = "Bbm7",
  Bbaug = "Bbaug",
  Bbdim = "Bbdim",
  Bb2 = "Bb2",
  Bb6 = "Bb6",
  Bb7 = "Bb7",
  Bbsus2 = "Bbsus2",
  Bbsus4 = "Bbsus4",
  // B
  BMajor = "BMajor",
  Bm = "Bm",
  Bm6 = "Bm6",
  Bm7 = "Bm7",
  Baug = "Baug",
  Bdim = "Bdim",
  B2 = "B2",
  B6 = "B6",
  B7 = "B7",
  Bsus2 = "Bsus2",
  Bsus4 = "Bsus4"
}

export enum TSpatternEnum {
  asc = "asc",
  des = "des",
  parallel = "parallel"
}
