export enum FSinstrumentEnum {
  acoustic_grand_piano = "acoustic_grand_piano",
  acoustic_guitar_nylon = "acoustic_guitar_nylon",
  acoustic_guitar_steel = "acoustic_guitar_steel",
  accordion = "accordion",
  acoustic_bass = "acoustic_bass",
  agogo = "agogo",
  alto_sax = "alto_sax",
  applause = "applause",
  bag_pipe = "bag_pipe",
  banjo = "banjo",
  baritone_sax = "baritone_sax",
  bassoon = "bassoon",
  bird_tweet = "bird_tweet",
  blown_bottle = "blown_bottle",
  brass_section = "brass_section",
  breath_noise = "breath_noise",
  bright_acoustic_piano = "bright_acoustic_piano",
  celesta = "celesta",
  cello = "cello",
  choir_aahs = "choir_aahs",
  church_organ = "church_organ",
  clarinet = "clarinet",
  clavichord = "clavichord",
  contrabass = "contrabass",
  distortion_guitar = "distortion_guitar",
  drawbar_organ = "drawbar_organ",
  dulcimer = "dulcimer",
  electric_bass_finger = "electric_bass_finger",
  electric_bass_pick = "electric_bass_pick",
  electric_grand_piano = "electric_grand_piano",
  electric_guitar_clean = "electric_guitar_clean",
  electric_guitar_jazz = "electric_guitar_jazz",
  electric_guitar_muted = "electric_guitar_muted",
  electric_piano_1 = "electric_piano_1",
  electric_piano_2 = "electric_piano_2",
  english_horn = "english_horn",
  fiddle = "fiddle",
  flute = "flute",
  french_horn = "french_horn",
  fretless_bass = "fretless_bass",
  fx_1_rain = "fx_1_rain",
  fx_2_soundtrack = "fx_2_soundtrack",
  fx_3_crystal = "fx_3_crystal",
  fx_4_atmosphere = "fx_4_atmosphere",
  fx_5_brightness = "fx_5_brightness",
  fx_6_goblins = "fx_6_goblins",
  fx_7_echoes = "fx_7_echoes",
  fx_8_scifi = "fx_8_scifi",
  glockenspiel = "glockenspiel",
  guitar_fret_noise = "guitar_fret_noise",
  guitar_harmonics = "guitar_harmonics",
  gunshot = "gunshot",
  harmonica = "harmonica",
  harpsichord = "harpsichord",
  helicopter = "helicopter",
  honkytonk_piano = "honkytonk_piano",
  kalimba = "kalimba",
  koto = "koto",
  lead_1_square = "lead_1_square",
  lead_2_sawtooth = "lead_2_sawtooth",
  lead_3_calliope = "lead_3_calliope",
  lead_4_chiff = "lead_4_chiff",
  lead_5_charang = "lead_5_charang",
  lead_6_voice = "lead_6_voice",
  lead_7_fifths = "lead_7_fifths",
  lead_8_bass_lead = "lead_8_bass_lead",
  marimba = "marimba",
  melodic_tom = "melodic_tom",
  music_box = "music_box",
  muted_trumpet = "muted_trumpet",
  oboe = "oboe",
  ocarina = "ocarina",
  orchestra_hit = "orchestra_hit",
  orchestral_harp = "orchestral_harp",
  overdriven_guitar = "overdriven_guitar",
  pad_1_new_age = "pad_1_new_age",
  pad_2_warm = "pad_2_warm",
  pad_3_polysynth = "pad_3_polysynth",
  pad_4_choir = "pad_4_choir",
  pad_5_bowed = "pad_5_bowed",
  pad_6_metallic = "pad_6_metallic",
  pad_7_halo = "pad_7_halo",
  pad_8_sweep = "pad_8_sweep",
  pan_flute = "pan_flute",
  percussive_organ = "percussive_organ",
  piccolo = "piccolo",
  pizzicato_strings = "pizzicato_strings",
  recorder = "recorder",
  reed_organ = "reed_organ",
  reverse_cymbal = "reverse_cymbal",
  rock_organ = "rock_organ",
  seashore = "seashore",
  shakuhachi = "shakuhachi",
  shamisen = "shamisen",
  shanai = "shanai",
  sitar = "sitar",
  slap_bass_1 = "slap_bass_1",
  slap_bass_2 = "slap_bass_2",
  soprano_sax = "soprano_sax",
  steel_drums = "steel_drums",
  string_ensemble_1 = "string_ensemble_1",
  string_ensemble_2 = "string_ensemble_2",
  synth_bass_1 = "synth_bass_1",
  synth_bass_2 = "synth_bass_2",
  synth_drum = "synth_drum",
  synth_voice = "synth_voice",
  synthbrass_1 = "synthbrass_1",
  synthbrass_2 = "synthbrass_2",
  synthstrings_1 = "synthstrings_1",
  synthstrings_2 = "synthstrings_2",
  taiko_drum = "taiko_drum",
  tango_accordion = "tango_accordion",
  telephone_ring = "telephone_ring",
  tenor_sax = "tenor_sax",
  timpani = "timpani",
  tinkle_bell = "tinkle_bell",
  tremolo_strings = "tremolo_strings",
  trombone = "trombone",
  trumpet = "trumpet",
  tuba = "tuba",
  tubular_bells = "tubular_bells",
  vibraphone = "vibraphone",
  viola = "viola",
  violin = "violin",
  voice_oohs = "voice_oohs",
  whistle = "whistle",
  woodblock = "woodblock",
  xylophone = "xylophone"
}

export const FSinstrumentList: FSinstrumentEnum[] = [
  FSinstrumentEnum.acoustic_grand_piano,
  FSinstrumentEnum.acoustic_guitar_nylon,
  FSinstrumentEnum.acoustic_guitar_steel,
  FSinstrumentEnum.accordion,
  FSinstrumentEnum.acoustic_bass,
  FSinstrumentEnum.agogo,
  FSinstrumentEnum.alto_sax,
  FSinstrumentEnum.applause,
  FSinstrumentEnum.bag_pipe,
  FSinstrumentEnum.banjo,
  FSinstrumentEnum.baritone_sax,
  FSinstrumentEnum.bassoon,
  FSinstrumentEnum.bird_tweet,
  FSinstrumentEnum.blown_bottle,
  FSinstrumentEnum.brass_section,
  FSinstrumentEnum.breath_noise,
  FSinstrumentEnum.bright_acoustic_piano,
  FSinstrumentEnum.celesta,
  FSinstrumentEnum.cello,
  FSinstrumentEnum.choir_aahs,
  FSinstrumentEnum.church_organ,
  FSinstrumentEnum.clarinet,
  FSinstrumentEnum.clavichord,
  FSinstrumentEnum.contrabass,
  FSinstrumentEnum.distortion_guitar,
  FSinstrumentEnum.drawbar_organ,
  FSinstrumentEnum.dulcimer,
  FSinstrumentEnum.electric_bass_finger,
  FSinstrumentEnum.electric_bass_pick,
  FSinstrumentEnum.electric_grand_piano,
  FSinstrumentEnum.electric_guitar_clean,
  FSinstrumentEnum.electric_guitar_jazz,
  FSinstrumentEnum.electric_guitar_muted,
  FSinstrumentEnum.electric_piano_1,
  FSinstrumentEnum.electric_piano_2,
  FSinstrumentEnum.english_horn,
  FSinstrumentEnum.fiddle,
  FSinstrumentEnum.flute,
  FSinstrumentEnum.french_horn,
  FSinstrumentEnum.fretless_bass,
  FSinstrumentEnum.fx_1_rain,
  FSinstrumentEnum.fx_2_soundtrack,
  FSinstrumentEnum.fx_3_crystal,
  FSinstrumentEnum.fx_4_atmosphere,
  FSinstrumentEnum.fx_5_brightness,
  FSinstrumentEnum.fx_6_goblins,
  FSinstrumentEnum.fx_7_echoes,
  FSinstrumentEnum.fx_8_scifi,
  FSinstrumentEnum.glockenspiel,
  FSinstrumentEnum.guitar_fret_noise,
  FSinstrumentEnum.guitar_harmonics,
  FSinstrumentEnum.gunshot,
  FSinstrumentEnum.harmonica,
  FSinstrumentEnum.harpsichord,
  FSinstrumentEnum.helicopter,
  FSinstrumentEnum.honkytonk_piano,
  FSinstrumentEnum.kalimba,
  FSinstrumentEnum.koto,
  FSinstrumentEnum.lead_1_square,
  FSinstrumentEnum.lead_2_sawtooth,
  FSinstrumentEnum.lead_3_calliope,
  FSinstrumentEnum.lead_4_chiff,
  FSinstrumentEnum.lead_5_charang,
  FSinstrumentEnum.lead_6_voice,
  FSinstrumentEnum.lead_7_fifths,
  FSinstrumentEnum.lead_8_bass_lead,
  FSinstrumentEnum.marimba,
  FSinstrumentEnum.melodic_tom,
  FSinstrumentEnum.music_box,
  FSinstrumentEnum.muted_trumpet,
  FSinstrumentEnum.oboe,
  FSinstrumentEnum.ocarina,
  FSinstrumentEnum.orchestra_hit,
  FSinstrumentEnum.orchestral_harp,
  FSinstrumentEnum.overdriven_guitar,
  FSinstrumentEnum.pad_1_new_age,
  FSinstrumentEnum.pad_2_warm,
  FSinstrumentEnum.pad_3_polysynth,
  FSinstrumentEnum.pad_4_choir,
  FSinstrumentEnum.pad_5_bowed,
  FSinstrumentEnum.pad_6_metallic,
  FSinstrumentEnum.pad_7_halo,
  FSinstrumentEnum.pad_8_sweep,
  FSinstrumentEnum.pan_flute,
  FSinstrumentEnum.percussive_organ,
  FSinstrumentEnum.piccolo,
  FSinstrumentEnum.pizzicato_strings,
  FSinstrumentEnum.recorder,
  FSinstrumentEnum.reed_organ,
  FSinstrumentEnum.reverse_cymbal,
  FSinstrumentEnum.rock_organ,
  FSinstrumentEnum.seashore,
  FSinstrumentEnum.shakuhachi,
  FSinstrumentEnum.shamisen,
  FSinstrumentEnum.shanai,
  FSinstrumentEnum.sitar,
  FSinstrumentEnum.slap_bass_1,
  FSinstrumentEnum.slap_bass_2,
  FSinstrumentEnum.soprano_sax,
  FSinstrumentEnum.steel_drums,
  FSinstrumentEnum.string_ensemble_1,
  FSinstrumentEnum.string_ensemble_2,
  FSinstrumentEnum.synth_bass_1,
  FSinstrumentEnum.synth_bass_2,
  FSinstrumentEnum.synth_drum,
  FSinstrumentEnum.synth_voice,
  FSinstrumentEnum.synthbrass_1,
  FSinstrumentEnum.synthbrass_2,
  FSinstrumentEnum.synthstrings_1,
  FSinstrumentEnum.synthstrings_2,
  FSinstrumentEnum.taiko_drum,
  FSinstrumentEnum.tango_accordion,
  FSinstrumentEnum.telephone_ring,
  FSinstrumentEnum.tenor_sax,
  FSinstrumentEnum.timpani,
  FSinstrumentEnum.tinkle_bell,
  FSinstrumentEnum.tremolo_strings,
  FSinstrumentEnum.trombone,
  FSinstrumentEnum.trumpet,
  FSinstrumentEnum.tuba,
  FSinstrumentEnum.tubular_bells,
  FSinstrumentEnum.vibraphone,
  FSinstrumentEnum.viola,
  FSinstrumentEnum.violin,
  FSinstrumentEnum.voice_oohs,
  FSinstrumentEnum.whistle,
  FSinstrumentEnum.woodblock,
  FSinstrumentEnum.xylophone
];
