export enum TSinstrumentEnum {
  acoustic_grand_piano = "acoustic_grand_piano",
  acoustic_guitar_nylon = "acoustic_guitar_nylon",
  acoustic_guitar_steel = "acoustic_guitar_steel",
  accordion = "accordion",
  acoustic_bass = "acoustic_bass",
  agogo = "agogo",
  alto_sax = "alto_sax",
  applause = "applause",
  bag_pipe = "bag_pipe",
  banjo = "banjo",
  baritone_sax = "baritone_sax",
  bassoon = "bassoon",
  bird_tweet = "bird_tweet",
  blown_bottle = "blown_bottle",
  brass_section = "brass_section",
  breath_noise = "breath_noise",
  bright_acoustic_piano = "bright_acoustic_piano",
  celesta = "celesta",
  cello = "cello",
  choir_aahs = "choir_aahs",
  church_organ = "church_organ",
  clarinet = "clarinet",
  clavichord = "clavichord",
  contrabass = "contrabass",
  distortion_guitar = "distortion_guitar",
  drawbar_organ = "drawbar_organ",
  dulcimer = "dulcimer",
  electric_bass_finger = "electric_bass_finger",
  electric_bass_pick = "electric_bass_pick",
  electric_grand_piano = "electric_grand_piano",
  electric_guitar_clean = "electric_guitar_clean",
  electric_guitar_jazz = "electric_guitar_jazz",
  electric_guitar_muted = "electric_guitar_muted",
  electric_piano_1 = "electric_piano_1",
  electric_piano_2 = "electric_piano_2",
  english_horn = "english_horn",
  fiddle = "fiddle",
  flute = "flute",
  french_horn = "french_horn",
  fretless_bass = "fretless_bass",
  fx_1_rain = "fx_1_rain",
  fx_2_soundtrack = "fx_2_soundtrack",
  fx_3_crystal = "fx_3_crystal",
  fx_4_atmosphere = "fx_4_atmosphere",
  fx_5_brightness = "fx_5_brightness",
  fx_6_goblins = "fx_6_goblins",
  fx_7_echoes = "fx_7_echoes",
  fx_8_scifi = "fx_8_scifi",
  glockenspiel = "glockenspiel",
  guitar_fret_noise = "guitar_fret_noise",
  guitar_harmonics = "guitar_harmonics",
  gunshot = "gunshot",
  harmonica = "harmonica",
  harpsichord = "harpsichord",
  helicopter = "helicopter",
  honkytonk_piano = "honkytonk_piano",
  kalimba = "kalimba",
  koto = "koto",
  lead_1_square = "lead_1_square",
  lead_2_sawtooth = "lead_2_sawtooth",
  lead_3_calliope = "lead_3_calliope",
  lead_4_chiff = "lead_4_chiff",
  lead_5_charang = "lead_5_charang",
  lead_6_voice = "lead_6_voice",
  lead_7_fifths = "lead_7_fifths",
  lead_8_bass_lead = "lead_8_bass_lead",
  marimba = "marimba",
  melodic_tom = "melodic_tom",
  music_box = "music_box",
  muted_trumpet = "muted_trumpet",
  oboe = "oboe",
  ocarina = "ocarina",
  orchestra_hit = "orchestra_hit",
  orchestral_harp = "orchestral_harp",
  overdriven_guitar = "overdriven_guitar",
  pad_1_new_age = "pad_1_new_age",
  pad_2_warm = "pad_2_warm",
  pad_3_polysynth = "pad_3_polysynth",
  pad_4_choir = "pad_4_choir",
  pad_5_bowed = "pad_5_bowed",
  pad_6_metallic = "pad_6_metallic",
  pad_7_halo = "pad_7_halo",
  pad_8_sweep = "pad_8_sweep",
  pan_flute = "pan_flute",
  percussive_organ = "percussive_organ",
  piccolo = "piccolo",
  pizzicato_strings = "pizzicato_strings",
  recorder = "recorder",
  reed_organ = "reed_organ",
  reverse_cymbal = "reverse_cymbal",
  rock_organ = "rock_organ",
  seashore = "seashore",
  shakuhachi = "shakuhachi",
  shamisen = "shamisen",
  shanai = "shanai",
  sitar = "sitar",
  slap_bass_1 = "slap_bass_1",
  slap_bass_2 = "slap_bass_2",
  soprano_sax = "soprano_sax",
  steel_drums = "steel_drums",
  string_ensemble_1 = "string_ensemble_1",
  string_ensemble_2 = "string_ensemble_2",
  synth_bass_1 = "synth_bass_1",
  synth_bass_2 = "synth_bass_2",
  synth_drum = "synth_drum",
  synth_voice = "synth_voice",
  synthbrass_1 = "synthbrass_1",
  synthbrass_2 = "synthbrass_2",
  synthstrings_1 = "synthstrings_1",
  synthstrings_2 = "synthstrings_2",
  taiko_drum = "taiko_drum",
  tango_accordion = "tango_accordion",
  telephone_ring = "telephone_ring",
  tenor_sax = "tenor_sax",
  timpani = "timpani",
  tinkle_bell = "tinkle_bell",
  tremolo_strings = "tremolo_strings",
  trombone = "trombone",
  trumpet = "trumpet",
  tuba = "tuba",
  tubular_bells = "tubular_bells",
  vibraphone = "vibraphone",
  viola = "viola",
  violin = "violin",
  voice_oohs = "voice_oohs",
  whistle = "whistle",
  woodblock = "woodblock",
  xylophone = "xylophone"
}

export const TSinstrumentList: TSinstrumentEnum[] = [
  TSinstrumentEnum.acoustic_grand_piano,
  TSinstrumentEnum.acoustic_guitar_nylon,
  TSinstrumentEnum.acoustic_guitar_steel,
  TSinstrumentEnum.accordion,
  TSinstrumentEnum.acoustic_bass,
  TSinstrumentEnum.agogo,
  TSinstrumentEnum.alto_sax,
  TSinstrumentEnum.applause,
  TSinstrumentEnum.bag_pipe,
  TSinstrumentEnum.banjo,
  TSinstrumentEnum.baritone_sax,
  TSinstrumentEnum.bassoon,
  TSinstrumentEnum.bird_tweet,
  TSinstrumentEnum.blown_bottle,
  TSinstrumentEnum.brass_section,
  TSinstrumentEnum.breath_noise,
  TSinstrumentEnum.bright_acoustic_piano,
  TSinstrumentEnum.celesta,
  TSinstrumentEnum.cello,
  TSinstrumentEnum.choir_aahs,
  TSinstrumentEnum.church_organ,
  TSinstrumentEnum.clarinet,
  TSinstrumentEnum.clavichord,
  TSinstrumentEnum.contrabass,
  TSinstrumentEnum.distortion_guitar,
  TSinstrumentEnum.drawbar_organ,
  TSinstrumentEnum.dulcimer,
  TSinstrumentEnum.electric_bass_finger,
  TSinstrumentEnum.electric_bass_pick,
  TSinstrumentEnum.electric_grand_piano,
  TSinstrumentEnum.electric_guitar_clean,
  TSinstrumentEnum.electric_guitar_jazz,
  TSinstrumentEnum.electric_guitar_muted,
  TSinstrumentEnum.electric_piano_1,
  TSinstrumentEnum.electric_piano_2,
  TSinstrumentEnum.english_horn,
  TSinstrumentEnum.fiddle,
  TSinstrumentEnum.flute,
  TSinstrumentEnum.french_horn,
  TSinstrumentEnum.fretless_bass,
  TSinstrumentEnum.fx_1_rain,
  TSinstrumentEnum.fx_2_soundtrack,
  TSinstrumentEnum.fx_3_crystal,
  TSinstrumentEnum.fx_4_atmosphere,
  TSinstrumentEnum.fx_5_brightness,
  TSinstrumentEnum.fx_6_goblins,
  TSinstrumentEnum.fx_7_echoes,
  TSinstrumentEnum.fx_8_scifi,
  TSinstrumentEnum.glockenspiel,
  TSinstrumentEnum.guitar_fret_noise,
  TSinstrumentEnum.guitar_harmonics,
  TSinstrumentEnum.gunshot,
  TSinstrumentEnum.harmonica,
  TSinstrumentEnum.harpsichord,
  TSinstrumentEnum.helicopter,
  TSinstrumentEnum.honkytonk_piano,
  TSinstrumentEnum.kalimba,
  TSinstrumentEnum.koto,
  TSinstrumentEnum.lead_1_square,
  TSinstrumentEnum.lead_2_sawtooth,
  TSinstrumentEnum.lead_3_calliope,
  TSinstrumentEnum.lead_4_chiff,
  TSinstrumentEnum.lead_5_charang,
  TSinstrumentEnum.lead_6_voice,
  TSinstrumentEnum.lead_7_fifths,
  TSinstrumentEnum.lead_8_bass_lead,
  TSinstrumentEnum.marimba,
  TSinstrumentEnum.melodic_tom,
  TSinstrumentEnum.music_box,
  TSinstrumentEnum.muted_trumpet,
  TSinstrumentEnum.oboe,
  TSinstrumentEnum.ocarina,
  TSinstrumentEnum.orchestra_hit,
  TSinstrumentEnum.orchestral_harp,
  TSinstrumentEnum.overdriven_guitar,
  TSinstrumentEnum.pad_1_new_age,
  TSinstrumentEnum.pad_2_warm,
  TSinstrumentEnum.pad_3_polysynth,
  TSinstrumentEnum.pad_4_choir,
  TSinstrumentEnum.pad_5_bowed,
  TSinstrumentEnum.pad_6_metallic,
  TSinstrumentEnum.pad_7_halo,
  TSinstrumentEnum.pad_8_sweep,
  TSinstrumentEnum.pan_flute,
  TSinstrumentEnum.percussive_organ,
  TSinstrumentEnum.piccolo,
  TSinstrumentEnum.pizzicato_strings,
  TSinstrumentEnum.recorder,
  TSinstrumentEnum.reed_organ,
  TSinstrumentEnum.reverse_cymbal,
  TSinstrumentEnum.rock_organ,
  TSinstrumentEnum.seashore,
  TSinstrumentEnum.shakuhachi,
  TSinstrumentEnum.shamisen,
  TSinstrumentEnum.shanai,
  TSinstrumentEnum.sitar,
  TSinstrumentEnum.slap_bass_1,
  TSinstrumentEnum.slap_bass_2,
  TSinstrumentEnum.soprano_sax,
  TSinstrumentEnum.steel_drums,
  TSinstrumentEnum.string_ensemble_1,
  TSinstrumentEnum.string_ensemble_2,
  TSinstrumentEnum.synth_bass_1,
  TSinstrumentEnum.synth_bass_2,
  TSinstrumentEnum.synth_drum,
  TSinstrumentEnum.synth_voice,
  TSinstrumentEnum.synthbrass_1,
  TSinstrumentEnum.synthbrass_2,
  TSinstrumentEnum.synthstrings_1,
  TSinstrumentEnum.synthstrings_2,
  TSinstrumentEnum.taiko_drum,
  TSinstrumentEnum.tango_accordion,
  TSinstrumentEnum.telephone_ring,
  TSinstrumentEnum.tenor_sax,
  TSinstrumentEnum.timpani,
  TSinstrumentEnum.tinkle_bell,
  TSinstrumentEnum.tremolo_strings,
  TSinstrumentEnum.trombone,
  TSinstrumentEnum.trumpet,
  TSinstrumentEnum.tuba,
  TSinstrumentEnum.tubular_bells,
  TSinstrumentEnum.vibraphone,
  TSinstrumentEnum.viola,
  TSinstrumentEnum.violin,
  TSinstrumentEnum.voice_oohs,
  TSinstrumentEnum.whistle,
  TSinstrumentEnum.woodblock,
  TSinstrumentEnum.xylophone
];
